pipeline:
  deployment:
    image: appleboy/drone-ssh:latest
    pull: true
    secrets:
      - source: regme_client_id
        target: rg_client_id
      - source: ssh_key
        target: ssh_key
      - source: rg_sentry_dsn
        target: rg_sentry_dsn

    host: nansen.online.ntnu.no
    username: root
    port: 22
    when:
      event: push
      branch: master
    environment:
      - RG_BASE=https://online.ntnu.no
      - NODE_ENV=production
    script:
      - cd /srv/www/regme
      - git pull
      - npm install
      - node /srv/www/regme/node_modules/webpack/bin/webpack.js